package Enums;

public enum Permissions {

    ADD_CAR_IMAGE,
    DELETE_CAR_IMAGE,
    SET_MAIN_CAR_IMAGE,
    ADD_CAR,
    ADD_CAR_TO_FAVORITES,
    ADD_REVIEW_TO_CAR,
    DELETE_CAR,
    DELETE_FAVORITE_CAR,
    GET_ALL_CARS,
    GET_CAR_BY_ID,
    GET_FAVORITE_CARS,
    GET_CAR_REVIEWS,
    RETURN_CAR,
    SEARCH_CARS,
    UPDATE_CAR_DETAILS,
    GET_CUSTOMER_PROFILE,
    UPDATE_CUSTOMER_PROFILE,
    ADD_PROFILE_IMAGE,
    DELETE_PROFILE_IMAGE,
    ADMIN_DASHBOARD_ACCESS,
    OVERDUE_RENTALS_ACCESS,
    BOOK_RENTAL,
    CANCEL_RENTAL,
    CUSTOMER_DASHBOARD_ACCESS,
    VIEW_RENTAL_HISTORY,
    UPDATE_RENTAL_STATUS,
    VIEW_PENDING_RENTALS;

}
